### ISSUE TITLE
Server always bind to localhost

### ISSUE THREAD

**Issue by fongtech** [zmqless/python-zeroless#33]
Server(port=12345) always bind to localhost, not possible to remote access it.

**Comment by x8lucas8x** [comment]
@fongtech I use the last version (1.0.0) of zeroless in a LAN setup and it works. Could you provide the snippets of both your client and server, so that I can try to pinpoint the problem?

**Comment by fongtech** [comment]
When I netstat, app binded to 0.0.0.0 which is correct. But server not getting the msg.
Server runs on Ubuntu 14.04 and client on MacOS 10.10

#netstat -tulpn      
tcp        0      0 0.0.0.0:12345           0.0.0.0:*               LISTEN      10868/python2.7 

client.py:
#!/opt/local/bin/python2.7
from zeroless import Client
client = Client()
client.connect('192.168.123.110',12345)
push = client.push()
for msg in [b"Msg1", b"Msg2", b"Msg3"]:
    push(msg)
    
server.py
#!/opt/local/bin/python2.7
import logging
from zeroless import Server, log
consoleHandler = logging.StreamHandler()
log.setLevel(logging.DEBUG)
log.addHandler(consoleHandler)
listen_for_push = Server(port=12345).pull()
for msg in listen_for_push:
    print msg

**Comment by x8lucas8x** [comment]
@fongtech If the ip you connect to is correct, your code is perfectly fine. Really, I don't know what could possibly be happening. Maybe you should try to use wireshark to double check if the packets are being sent and/or received.
